"""
Vault storage for encrypted env files.

Vault layout (JSON inside encrypted payload):
{
  "version": 1,
  "envs": {
    "<project>": {
      "vars": {"KEY": "value", ...},
      "description": "..."
    }
  }
}

On disk the vault is stored as:
  ~/.env-manager/vault.enc  — encrypted bytes (salt + fernet token)
"""

import json
import os
from pathlib import Path

from .crypto import encrypt, decrypt

VAULT_DIR = Path.home() / ".env-manager"
VAULT_FILE = VAULT_DIR / "vault.enc"


def _empty_vault() -> dict:
    return {"version": 1, "envs": {}}


def load_vault(password: str) -> dict:
    """Load and decrypt the vault. Returns empty vault if file doesn't exist."""
    if not VAULT_FILE.exists():
        return _empty_vault()
    raw = VAULT_FILE.read_bytes()
    text = decrypt(raw, password)
    return json.loads(text)


def save_vault(vault: dict, password: str) -> None:
    """Encrypt and persist the vault."""
    VAULT_DIR.mkdir(mode=0o700, parents=True, exist_ok=True)
    data = json.dumps(vault, ensure_ascii=False, indent=2)
    encrypted = encrypt(data, password)
    VAULT_FILE.write_bytes(encrypted)
    VAULT_FILE.chmod(0o600)


def list_projects(vault: dict) -> list[str]:
    return sorted(vault.get("envs", {}).keys())


def get_project(vault: dict, project: str) -> dict | None:
    return vault.get("envs", {}).get(project)


def set_var(vault: dict, project: str, key: str, value: str) -> None:
    vault.setdefault("envs", {}).setdefault(project, {"vars": {}, "description": ""})
    vault["envs"][project]["vars"][key] = value


def delete_var(vault: dict, project: str, key: str) -> bool:
    env = vault.get("envs", {}).get(project, {})
    if key in env.get("vars", {}):
        del env["vars"][key]
        return True
    return False


def delete_project(vault: dict, project: str) -> bool:
    if project in vault.get("envs", {}):
        del vault["envs"][project]
        return True
    return False


def set_description(vault: dict, project: str, description: str) -> None:
    vault.setdefault("envs", {}).setdefault(project, {"vars": {}, "description": ""})
    vault["envs"][project]["description"] = description


def export_dotenv(vault: dict, project: str) -> str:
    """Export project vars as .env file content."""
    env = vault.get("envs", {}).get(project)
    if not env:
        return ""
    lines = [f"# {project} — generated by env-manager"]
    for k, v in sorted(env.get("vars", {}).items()):
        # Quote values that contain spaces or special chars
        if any(c in v for c in (' ', '"', "'", '\n', '$', '\\', '`')):
            escaped = v.replace('\\', '\\\\').replace('"', '\\"')
            lines.append(f'{k}="{escaped}"')
        else:
            lines.append(f"{k}={v}")
    return "\n".join(lines) + "\n"


def import_dotenv(vault: dict, project: str, content: str) -> int:
    """Parse .env content and import variables. Returns count of imported vars."""
    count = 0
    for line in content.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        # Strip surrounding quotes from value
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in ('"', "'"):
            value = value[1:-1]
        if key:
            set_var(vault, project, key, value)
            count += 1
    return count
