"""
Vault storage for encrypted env files.

Vault layout (JSON inside encrypted payload):
{
  "version": 1,
  "envs": {
    "<project>": {
      "vars": {"KEY": "value", ...},
      "description": "..."
    }
  }
}

On disk the vault is stored as:
  ~/.env-manager/vault.enc  — encrypted bytes (salt + fernet token)
  Override location with ENV_MANAGER_VAULT env var.
"""

import json
from pathlib import Path

from .config import VAULT_DIR, VAULT_FILE, VAULT_VERSION
from .crypto import encrypt, decrypt
from .logger import get_logger
from .validators import validate_key, ValidationError

log = get_logger("store")

# Re-export so cli.py and tests can import from store as before
__all__ = [
    "VAULT_DIR", "VAULT_FILE",
    "load_vault", "save_vault",
    "list_projects", "get_project",
    "set_var", "delete_var", "delete_project", "set_description",
    "export_dotenv", "import_dotenv",
    "copy_project", "rename_project",
]


def _empty_vault() -> dict:
    return {"version": VAULT_VERSION, "envs": {}}


def load_vault(password: str) -> dict:
    """Load and decrypt the vault. Returns empty vault if file doesn't exist."""
    if not VAULT_FILE.exists():
        log.debug("Vault file does not exist yet, returning empty vault")
        return _empty_vault()
    raw = VAULT_FILE.read_bytes()
    if len(raw) == 0:
        raise ValueError("Vault file is empty or corrupted")
    log.debug("Loading vault from %s (%d bytes)", VAULT_FILE, len(raw))
    text = decrypt(raw, password)
    try:
        vault = json.loads(text)
    except json.JSONDecodeError as exc:
        raise ValueError("Vault data is corrupted (invalid JSON)") from exc
    if "envs" not in vault:
        raise ValueError("Vault data is corrupted (missing 'envs' key)")
    return vault


def save_vault(vault: dict, password: str) -> None:
    """Encrypt and persist the vault."""
    VAULT_DIR.mkdir(mode=0o700, parents=True, exist_ok=True)
    data = json.dumps(vault, ensure_ascii=False, indent=2)
    encrypted = encrypt(data, password)
    VAULT_FILE.write_bytes(encrypted)
    VAULT_FILE.chmod(0o600)
    log.debug("Vault saved (%d bytes)", len(encrypted))


def list_projects(vault: dict) -> list[str]:
    return sorted(vault.get("envs", {}).keys())


def get_project(vault: dict, project: str) -> dict | None:
    return vault.get("envs", {}).get(project)


def set_var(vault: dict, project: str, key: str, value: str) -> None:
    vault.setdefault("envs", {}).setdefault(project, {"vars": {}, "description": ""})
    vault["envs"][project]["vars"][key] = value
    log.debug("Set %s in project '%s'", key, project)


def delete_var(vault: dict, project: str, key: str) -> bool:
    env = vault.get("envs", {}).get(project, {})
    if key in env.get("vars", {}):
        del env["vars"][key]
        log.debug("Deleted %s from project '%s'", key, project)
        return True
    return False


def delete_project(vault: dict, project: str) -> bool:
    if project in vault.get("envs", {}):
        del vault["envs"][project]
        log.debug("Deleted project '%s'", project)
        return True
    return False


def set_description(vault: dict, project: str, description: str) -> None:
    vault.setdefault("envs", {}).setdefault(project, {"vars": {}, "description": ""})
    vault["envs"][project]["description"] = description


def copy_project(vault: dict, source: str, dest: str) -> int:
    """Copy all vars from source project to dest. Returns number of vars copied."""
    src = vault.get("envs", {}).get(source)
    if src is None:
        raise KeyError(f"Project '{source}' not found")
    vault.setdefault("envs", {}).setdefault(dest, {"vars": {}, "description": ""})
    vars_to_copy = dict(src.get("vars", {}))
    vault["envs"][dest]["vars"].update(vars_to_copy)
    log.debug("Copied %d vars from '%s' to '%s'", len(vars_to_copy), source, dest)
    return len(vars_to_copy)


def rename_project(vault: dict, old_name: str, new_name: str) -> None:
    """Rename a project. Raises KeyError if old_name not found or new_name exists."""
    if old_name not in vault.get("envs", {}):
        raise KeyError(f"Project '{old_name}' not found")
    if new_name in vault.get("envs", {}):
        raise ValueError(f"Project '{new_name}' already exists")
    vault["envs"][new_name] = vault["envs"].pop(old_name)
    log.debug("Renamed project '%s' → '%s'", old_name, new_name)


def export_dotenv(vault: dict, project: str) -> str:
    """Export project vars as .env file content."""
    env = vault.get("envs", {}).get(project)
    if not env:
        return ""
    lines = [f"# {project} — generated by env-manager"]
    for k, v in sorted(env.get("vars", {}).items()):
        if any(c in v for c in (' ', '"', "'", '\n', '$', '\\', '`')):
            escaped = v.replace('\\', '\\\\').replace('"', '\\"')
            lines.append(f'{k}="{escaped}"')
        else:
            lines.append(f"{k}={v}")
    return "\n".join(lines) + "\n"


def import_dotenv(vault: dict, project: str, content: str) -> int:
    """Parse .env content and import variables. Returns count of imported vars."""
    parsed_items = []
    for line_number, line in enumerate(content.splitlines(), start=1):
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        # Handle 'export KEY=value' format
        if line.startswith("export "):
            line = line[7:].lstrip()
        if "=" not in line:
            continue
        key, _, value = line.partition("=")
        key = key.strip()
        value = value.strip()
        # Strip surrounding matching quotes
        if len(value) >= 2 and value[0] == value[-1] and value[0] in ('"', "'"):
            value = value[1:-1]
            # Unescape common backslash sequences inside double-quoted values
            value = value.replace('\\"', '"').replace('\\\\', '\\').replace('\\n', '\n').replace('\\t', '\t')
        if key:
            try:
                validate_key(key)
            except ValidationError as exc:
                raise ValidationError(f"Invalid key on line {line_number}: {exc}") from exc
            parsed_items.append((key, value))

    for key, value in parsed_items:
        set_var(vault, project, key, value)
    return len(parsed_items)
